version: '2'

services:
  app:
    build: .
    command: npm run start
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 30
