version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: node index.js
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis
    container_name: cache
    ports:
      - '6379:6379'
